kakao:
  redirect_uri: ${KAKAO_REDIRECT_URI}
  api_key: ${KAKAO_API_KEY}

jwt:
  secret_key: ${JWT_SECRET_KEY}

spring:
  application:
    name: opensource_server
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${DATASOURCE_URL}?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC  # UTF-8 설정 추가
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
      path: /h2-console

server:
  port: ${PORT}
  ssl:
    enabled: ${SSL_ENABLED}
    key-store: /etc/letsencrypt/keystore.p12
    key-store-password: ${SSL_KEY}
    key-store-type: PKCS12
    key-alias: tomcat

apple:
  team_id: ${APPLE_TEAM_ID}
  key_id: ${APPLE_KEY_ID}
  client_id: ${APPLE_CLIENT_ID}
  redirect_uri: ${APPLE_REDIRECT_URI}
  private_key: ${APPLE_PRIVATE_KEY}
