kakao:
  redirect_uri: http://localhost:8080/auth/login/kakao/callback
  api_key: 8dae628050e01f9cbec0a13c8511868e

jwt:
  secret_key: f6b52d55e1f34ae244b812a352098ab9e0f9c3f42817d8a28997bc74d78c54b6

spring:
  application:
    name: opensource_server
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/opensource?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  ssl:
    enabled: false
    key-store: /etc/letsencrypt/keystore.p12
    key-store-password: asdf1234
    key-store-type: PKCS12
    key-alias: tomcat

apple:
  team_id: BBVZV8T99P
  key_id: 4X8JUMKS2U
  client_id: io.tuist.SSP-iOS
  redirect_uri: https://leeyj.xyz/auth/login/apple/callback
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgL4cE2XT54i89K8Ny
    iYtQ8X+/yoVFgofXDKkrHX2UYNKgCgYIKoZIzj0DAQehRANCAAR1MANTCrdZlF7v
    ywMMDQPq9u8yPX1n7GgMhggXEHKP6AqLyS5lR7Ko14u6zT2c47CCYUckQZvHEpwX
    4sUDu06E
    -----END PRIVATE KEY-----
