kakao:
  redirect_uri: ${KAKAO_REDIRECT_URI}
  api_key: ${KAKAO_API_KEY}

jwt:
  secret_key: ${JWT_SECRET_KEY}

spring:
  application:
    name: opensource_server
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  ssl:
    enabled: false

apple:
  team_id: ${APPLE_TEAM_ID}
  key_id: ${APPLE_KEY_ID}
  client_id: ${APPLE_CLIENT_ID}
  redirect_uri: ${APPLE_REDIRECT_URI}
  private_key: ${APPLE_PRIVATE_KEY}