kakao:
    redirect_uri: ${KAKAO_REDIRECT_URI}
    api_key: ${KAKAO_API_KEY}

jwt:
  secret_key: ${JWT_SECRET_KEY}

spring:
  application:
    name: opensource_server
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${PORT}
  ssl:
    enabled: ${SSL_ENABLED}
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY}
    key-store-type: PKCS12
    key-alias: tomcat